#!/bin/bash sourced
## Manage the host tree generated by a buildroot-based build.
## 
## Arguments:
##
##     --clean-only 
##     
##     [ --build ] [ --clean-first ]
## 
## Typical uses:
##
##     buildroot_host_tree
##     buildroot_host_tree --build
##     
##     buildroot_host_tree --clean-only
##     buildroot_host_tree --clean-first
## 

[ -z "$buildroot_cli_handler_for_host_tree_functions_p" ] || return 0

buildroot_cli_handler_for_host_tree_functions_p=t

buildroot_cli_handler_for_host_tree_debug_p=

##

source buildroot_api_host_tree.functions.sh

##

function buildroot_cli_handler_for_host_tree() { # ...

	load_buildroot_config

	buildroot_host_tree "$@"
}

