#!/bin/bash sourced
## Manage the target tree generated by a buildroot-based build.
## 
## Arguments:
##
##     --clean-only 
##     
##     [ --build ] [ --clean-first ]
## 
## Typical uses:
##
##     buildroot_target_tree
##     buildroot_target_tree --build
##     
##     buildroot_target_tree --clean-only
##     buildroot_target_tree --clean-first
## 

[ -z "$buildroot_cli_handler_for_target_tree_functions_p" ] || return 0

buildroot_cli_handler_for_target_tree_functions_p=t

buildroot_cli_handler_for_target_tree_debug_p=

##

source buildroot_api_target_tree.functions.sh

##

function buildroot_cli_handler_for_target_tree() { # ...

	load_buildroot_config

	buildroot_target_tree "$@"
}

